#!/usr/bin/env python3

import matplotlib.pyplot as plt
from control.models.jet_engine import JetEngine
from control.controller import Controller

INITIAL_CONDITIONS = [5.37, 0.34]
T_FINAL = 3.0
PERIOD = 0.01

if __name__ == "__main__":
    # construct JetEngine class

    print("Constructing jet engine model.")
    model = JetEngine(INITIAL_CONDITIONS)

    print ("Constructing periodic controller.")
    controller = Controller(PERIOD, model, model.calculateCommand)

    print("Simulating...")
    t_periodic, r_periodic = controller.execute_periodic(T_FINAL)

    # also get the analog "perfect world" respone
    t_perfect, r_perfect = model.analogResponse(T_FINAL, INITIAL_CONDITIONS, t_periodic)

    # plot the response
    plt.plot(t_perfect, r_perfect[:, 0], 'b')
    plt.plot(t_perfect, r_perfect[:, 1], 'r')
    plt.plot(t_periodic, r_periodic[:, 0], 'b*', markersize = 1)
    plt.plot(t_periodic, r_periodic[:, 1], 'r*', markersize = 1)
    plt.xlabel("Time (s)")
    plt.ylabel("State")
    plt.legend(["x1 (perfect)", "x2 (perfect)", "x1 (periodic)", "x2 (periodic)"])
    plt.show()