#!/usr/bin/env python3

import matplotlib.pyplot as plt
from models.jet_engine import JetEngine
from controller.periodic import PeriodicController

if __name__ == "__main__":
    # construct JetEngine class

    print("Constructing jet engine model.")
    model = JetEngine([5.37, 0.34])

    print ("Constructing periodic controller.")
    controller = PeriodicController(0.01, model, model.calculateCommand)

    print("Simulating...")
    t_periodic, r_periodic = controller.execute(3)

    # also get the analog "perfect world" respone
    t_perfect, r_perfect = model.analogResponse(3, [5.37, 0.34], t_periodic)

    # plot the response
    plt.plot(t_perfect, r_perfect[:, 0], 'b')
    plt.plot(t_perfect, r_perfect[:, 1], 'r')
    plt.plot(t_periodic, r_periodic[:, 0], 'b*', markersize = 1)
    plt.plot(t_periodic, r_periodic[:, 1], 'r*', markersize = 1)
    plt.xlabel("Time (s)")
    plt.ylabel("State")
    plt.legend(["x1 (perfect)", "x2 (perfect)", "x1 (periodic)", "x2 (periodic)"])
    plt.show()